<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var Mozg_Cielo_Block_Form_Cc $this */; ?>
<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_owner]\"" : "data-encrypted-name=\"holderName\""); ?> value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" maxlength="100" />
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_type"><?php echo Mage::helper('payment')->__('Credit Card Type') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_cc_type" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_type]\"" : ""); ?> title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_number" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_number]\"" : " data-encrypted-name=\"number\""); ?> title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" maxlength="23"/>
            <?php if ($this->isCseEnabled()): ?>
                <input type="hidden" id="payment_cc_type_cse" name="payment[cc_type]" />
                <input type="hidden" id="payment_cc_number_cse" name="payment[cc_number]" />
            <?php endif; ?>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>

            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_exp_month]\"" : "data-encrypted-name=\"expiryMonth\""); ?> class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_exp_year]\"" : "data-encrypted-name=\"expiryYear\""); ?> class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>

                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_cid]\"" : "data-encrypted-name=\"cvc\""); ?> value="" maxlength="4" />
                </div>
            </div>
        </li>
    <?php endif; ?>
    <?php if($this->hasInstallments()): ?>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_installments" name="payment[additional_data]" class="number required-entry">
                        <?php foreach ($this->getPossibleInstallments() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
    <?php endif;?>
</ul>

    <script type="text/javascript">

        // easter_egg

        Event.observe($('<?php echo $_code ?>_cc_number'), 'dblclick', <?php echo $_code ?>_easter_egg);

        function <?php echo $_code ?>_easter_egg(event){

            console.log(arguments.callee.name);

            //console.dir(event);

            var element = event.element();

            //console.log(event.shiftKey);

            if(!event.shiftKey){
                return false;
            }

            console.log($('<?php echo $_code ?>_cc_number'));


            // NPM

            // https://www.npmjs.com/package/random-item

            var randomItem = require('random-item');
             
            var random_item = randomItem(['Visa', 'MasterCard', 'Amex', 'Diners', 'Discover', 'JCB']);

            console.log(random_item);

            // https://www.npmjs.com/package/creditcardgenerator

            const creditcardgenerator = require('creditcardgenerator');

            var creditcard_json = creditcardgenerator.create(random_item);

            var random_creditcard = creditcard_json.number;

            console.log(random_creditcard);

            // https://www.npmjs.com/package/random-month

            var randomMonth = require('random-month');

            var random_month = randomMonth();

            console.log(random_month);

            // https://www.npmjs.com/package/random-year

            var randomYear = require('random-year');

            var random_year = randomYear({ min: 2017, max: 2026 });

            console.log(random_year);

            // https://github.com/mock-end/random-natural

            var randomNatural = require('random-natural');

            var random_number = randomNatural({ min: 100, max: 999 });

            console.log(random_number);

            // https://www.npmjs.com/package/random-fullname

            var randomFullName = require('random-fullname');             

            var random_fullname = randomFullName();

            console.log(random_fullname);

            //

            $('<?php echo $_code ?>_cc_number').value = random_creditcard;
            $('<?php echo $_code ?>_cc_owner').value = random_fullname;
            $('<?php echo $_code ?>_cc_cid').value = random_number;
            $('<?php echo $_code ?>_expiration').value = random_month;
            $('<?php echo $_code ?>_expiration_yr').value = random_year;

            $('<?php echo $_code ?>_cc_number').triggerEvent('change');
            $('<?php echo $_code ?>_cc_number').triggerEvent('keyup');

        }

        console.log('<?php echo $_code ?>');

    </script>